version: '3.7'

services:
  backend_dev:
    container_name: blog_backend_dev
    image: juanpablopiano/blog-backend-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
  backend_prod:
    container_name: blog_backend_prod
    image: juanpablopiano/blog-backend-prod:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env

networks:
  nestjs-network:
